spring.application.name=upc-pre-202501-SI657-3587-LoremIpsum

spring.main.allow-circular-references=true

# Spring Data Source Configuration
spring.datasource.url=jdbc:postgresql://postgres:uPCaXuONbdaFEZIaJPTHhelXDiLYMYPu@turntable.proxy.rlwy.net:33362/railway
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.jpa.hibernate.naming.physical-strategy=upc.LoremIpsum.lawconnectplatform.shared.domain.model.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretKeyForTokenJWT
authorization.jwt.expiration.days=7